name: Build NuGet package

env:
  INNO_VERSION: 6.2.2

on: [push, pull_request]

jobs:
  build:
    name: Build package
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ./InnoSetup.Cli.build.ps1 -Version ${{ env.INNO_VERSION }} Install-InnoSetup

    - name: Pack
      run: ./InnoSetup.Cli.build.ps1 -Version ${{ env.INNO_VERSION }} Pack

    - name: Test
      run: ./InnoSetup.Cli.build.ps1 -Version ${{ env.INNO_VERSION }} Test

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget-package
        path: "./nupkg/*.nupkg"

  publish:
    name: Publish release to NuGet
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: build
    steps:
      - name: Fetch artifact
        uses: actions/download-artifact@v2
        with:
          name: nuget-package

      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-api-key-source: https://www.nuget.org/api/v2/package

      - name: Publish to NuGet
        run: nuget push *.nupkg -Source https://www.nuget.org/api/v2/package
